import json, os

def make_nb(cells):
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.0"}
        },
        "cells": cells
    }

def md(id, src):
    return {"cell_type": "markdown", "id": id, "metadata": {}, "source": src}

def code(id, src):
    return {"cell_type": "code", "id": id, "metadata": {}, "source": src, "outputs": [], "execution_count": None}

# ── L01: Getting Started ──
cells_01 = [
    md("cell-001", [
        "# DAM - Lesson 1: Getting Started with Python for Data\n",
        "**Code2College | Data Analysis & Management**\n",
        "\n",
        "Estimated time: 90 minutes\n",
        "\n",
        "Welcome to the Data Analysis & Management course! In this notebook, you'll review Python fundamentals and build a grade calculator program."
    ]),
    md("cell-002", [
        "## Learning Objectives\n",
        "\n",
        "By the end of this lesson, you will be able to:\n",
        "- Create variables and use Python data types (strings, integers, floats, booleans)\n",
        "- Define and call functions with parameters and return values\n",
        "- Use lists, loops, and conditionals to process data\n",
        "- Build a complete grade calculator program using f-strings for output"
    ]),
    md("cell-003", [
        "## Exercise 1: Variables and Data Types\n",
        "\n",
        "Create variables to store information about a student. Practice using different data types."
    ]),
    code("cell-004", [
        "# Exercise 1: Variables and Data Types\n",
        "# Create the following variables:\n",
        "#   student_name  -> a string with your name\n",
        "#   age           -> an integer\n",
        "#   gpa           -> a float\n",
        "#   is_enrolled   -> a boolean\n",
        "\n",
        "# TODO: your code here\n",
        "student_name = \n",
        "age = \n",
        "gpa = \n",
        "is_enrolled = \n",
        "\n",
        "# Print each variable and its type\n",
        "# TODO: your code here\n",
        "# Example: print(f\"{student_name} is a {type(student_name)}\")\n",
        "\n",
        "\n",
        "# ANSWER:\n",
        "# student_name = \"Alex Johnson\"\n",
        "# age = 17\n",
        "# gpa = 3.75\n",
        "# is_enrolled = True\n",
        "# print(f\"{student_name} is a {type(student_name)}\")\n",
        "# print(f\"{age} is a {type(age)}\")\n",
        "# print(f\"{gpa} is a {type(gpa)}\")\n",
        "# print(f\"{is_enrolled} is a {type(is_enrolled)}\")"
    ]),
    md("cell-005", [
        "## Exercise 2: Functions\n",
        "\n",
        "Functions let us reuse code. Write a function that takes a student's name and score, then returns a greeting message."
    ]),
    code("cell-006", [
        "# Exercise 2: Writing Functions\n",
        "# Define a function called 'greet_student' that:\n",
        "#   - Takes two parameters: name (str) and score (int)\n",
        "#   - Returns an f-string: \"Hello, {name}! Your score is {score}.\"\n",
        "\n",
        "# TODO: your code here\n",
        "def greet_student(name, score):\n",
        "    pass  # Replace this with your return statement\n",
        "\n",
        "# Test your function\n",
        "print(greet_student(\"Maria\", 95))\n",
        "print(greet_student(\"James\", 82))\n",
        "\n",
        "# ANSWER:\n",
        "# def greet_student(name, score):\n",
        "#     return f\"Hello, {name}! Your score is {score}.\""
    ]),
    md("cell-007", [
        "## Exercise 3: Lists and Loops\n",
        "\n",
        "Lists store collections of data. Use a `for` loop to process a list of test scores."
    ]),
    code("cell-008", [
        "# Exercise 3: Lists and Loops\n",
        "# Given this list of test scores:\n",
        "scores = [85, 92, 78, 95, 88, 73, 90]\n",
        "\n",
        "# Task 1: Use a for loop to print each score\n",
        "# TODO: your code here\n",
        "\n",
        "\n",
        "# Task 2: Use a for loop to calculate the total of all scores\n",
        "total = 0\n",
        "# TODO: your code here\n",
        "\n",
        "print(f\"Total: {total}\")\n",
        "\n",
        "# Task 3: Calculate the average\n",
        "# TODO: your code here\n",
        "average = \n",
        "print(f\"Average: {average}\")\n",
        "\n",
        "# ANSWER:\n",
        "# for score in scores:\n",
        "#     print(score)\n",
        "# total = 0\n",
        "# for score in scores:\n",
        "#     total += score\n",
        "# print(f\"Total: {total}\")\n",
        "# average = total / len(scores)\n",
        "# print(f\"Average: {average}\")"
    ]),
    md("cell-009", [
        "## Exercise 4: Conditionals\n",
        "\n",
        "Use `if/elif/else` to assign letter grades based on a numeric score."
    ]),
    code("cell-010", [
        "# Exercise 4: Conditionals\n",
        "# Write a function called 'get_letter_grade' that:\n",
        "#   - Takes a numeric score (0-100)\n",
        "#   - Returns the letter grade:\n",
        "#     90-100 = 'A', 80-89 = 'B', 70-79 = 'C', 60-69 = 'D', below 60 = 'F'\n",
        "\n",
        "# TODO: your code here\n",
        "def get_letter_grade(score):\n",
        "    pass  # Replace with if/elif/else logic\n",
        "\n",
        "# Test your function\n",
        "print(get_letter_grade(95))  # Should print 'A'\n",
        "print(get_letter_grade(83))  # Should print 'B'\n",
        "print(get_letter_grade(72))  # Should print 'C'\n",
        "print(get_letter_grade(65))  # Should print 'D'\n",
        "print(get_letter_grade(45))  # Should print 'F'\n",
        "\n",
        "# ANSWER:\n",
        "# def get_letter_grade(score):\n",
        "#     if score >= 90:\n",
        "#         return 'A'\n",
        "#     elif score >= 80:\n",
        "#         return 'B'\n",
        "#     elif score >= 70:\n",
        "#         return 'C'\n",
        "#     elif score >= 60:\n",
        "#         return 'D'\n",
        "#     else:\n",
        "#         return 'F'"
    ]),
    md("cell-011", [
        "## Exercise 5: Grade Calculator Program\n",
        "\n",
        "Now put it all together! Build a complete grade calculator that:\n",
        "1. Takes a list of student names and their scores\n",
        "2. Calculates each student's average\n",
        "3. Assigns a letter grade\n",
        "4. Prints a formatted report using f-strings"
    ]),
    code("cell-012", [
        "# Exercise 5: Complete Grade Calculator\n",
        "# Student data: each student has a name and a list of scores\n",
        "students = {\n",
        "    \"Maria\": [85, 92, 78],\n",
        "    \"James\": [90, 88, 95],\n",
        "    \"Aisha\": [72, 68, 75],\n",
        "    \"Carlos\": [95, 98, 92],\n",
        "    \"Priya\": [60, 55, 65]\n",
        "}\n",
        "\n",
        "# Step 1: Create a function to calculate the average of a list of scores\n",
        "def calculate_average(scores):\n",
        "    # TODO: your code here\n",
        "    pass\n",
        "\n",
        "# Step 2: Reuse your get_letter_grade function from Exercise 4\n",
        "# (copy it here or re-define it)\n",
        "def get_letter_grade(score):\n",
        "    # TODO: your code here\n",
        "    pass\n",
        "\n",
        "# Step 3: Loop through each student, calculate average, get grade, print report\n",
        "print(\"=\" * 45)\n",
        "print(f\"{'Student':<15} {'Average':>8} {'Grade':>6}\")\n",
        "print(\"=\" * 45)\n",
        "\n",
        "for name, scores in students.items():\n",
        "    avg = calculate_average(scores)\n",
        "    grade = get_letter_grade(avg)\n",
        "    # TODO: print a formatted line using f-string\n",
        "    # Example output: Maria             85.0      B\n",
        "    pass\n",
        "\n",
        "print(\"=\" * 45)\n",
        "\n",
        "# ANSWER:\n",
        "# def calculate_average(scores):\n",
        "#     return sum(scores) / len(scores)\n",
        "#\n",
        "# def get_letter_grade(score):\n",
        "#     if score >= 90: return 'A'\n",
        "#     elif score >= 80: return 'B'\n",
        "#     elif score >= 70: return 'C'\n",
        "#     elif score >= 60: return 'D'\n",
        "#     else: return 'F'\n",
        "#\n",
        "# for name, scores in students.items():\n",
        "#     avg = calculate_average(scores)\n",
        "#     grade = get_letter_grade(avg)\n",
        "#     print(f\"{name:<15} {avg:>8.1f} {grade:>6}\")"
    ]),
    md("cell-013", [
        "## Submission\n",
        "\n",
        "Great work completing Lesson 1! To get credit:\n",
        "\n",
        "1. Make sure all exercises above are completed\n",
        "2. Save this notebook (File > Save a copy in Drive)\n",
        "3. Return to **HireWheel** and paste your notebook URL\n",
        "4. Answer the exit ticket questions on the lesson page"
    ])
]

# ── L02: NumPy Arrays ──
cells_02 = [
    md("cell-001", [
        "# DAM - Lesson 2: NumPy Arrays\n",
        "**Code2College | Data Analysis & Management**\n",
        "\n",
        "Estimated time: 100 minutes\n",
        "\n",
        "NumPy is the foundation of data science in Python. In this notebook, you'll learn to create, manipulate, and analyze arrays."
    ]),
    md("cell-002", [
        "## Learning Objectives\n",
        "\n",
        "By the end of this lesson, you will be able to:\n",
        "- Create NumPy arrays using 5 different methods\n",
        "- Perform element-wise math operations on arrays\n",
        "- Work with 2D arrays (matrices)\n",
        "- Use slicing to select portions of an array\n",
        "- Apply boolean indexing to filter array elements\n",
        "- Compute aggregate statistics (mean, sum, max, min, std)"
    ]),
    code("cell-003", [
        "# Setup: Import NumPy\n",
        "import numpy as np\n",
        "\n",
        "print(f\"NumPy version: {np.__version__}\")\n",
        "print(\"NumPy imported successfully!\")"
    ]),
    md("cell-004", [
        "## Exercise 1: Array Creation (5 Methods)\n",
        "\n",
        "NumPy provides many ways to create arrays. Practice each method below."
    ]),
    code("cell-005", [
        "# Exercise 1: Create arrays using 5 different methods\n",
        "\n",
        "# Method 1: np.array() - create from a Python list\n",
        "# TODO: Create an array from the list [10, 20, 30, 40, 50]\n",
        "arr1 = \n",
        "print(\"From list:\", arr1)\n",
        "\n",
        "# Method 2: np.zeros() - create array of zeros\n",
        "# TODO: Create an array of 5 zeros\n",
        "arr2 = \n",
        "print(\"Zeros:\", arr2)\n",
        "\n",
        "# Method 3: np.ones() - create array of ones\n",
        "# TODO: Create an array of 4 ones\n",
        "arr3 = \n",
        "print(\"Ones:\", arr3)\n",
        "\n",
        "# Method 4: np.arange() - create a range of values\n",
        "# TODO: Create an array from 0 to 9 (like range(10))\n",
        "arr4 = \n",
        "print(\"Range:\", arr4)\n",
        "\n",
        "# Method 5: np.linspace() - create evenly spaced values\n",
        "# TODO: Create 5 evenly spaced values between 0 and 1\n",
        "arr5 = \n",
        "print(\"Linspace:\", arr5)\n",
        "\n",
        "# ANSWER:\n",
        "# arr1 = np.array([10, 20, 30, 40, 50])\n",
        "# arr2 = np.zeros(5)\n",
        "# arr3 = np.ones(4)\n",
        "# arr4 = np.arange(10)\n",
        "# arr5 = np.linspace(0, 1, 5)"
    ]),
    md("cell-006", [
        "## Exercise 2: Element-Wise Math Operations\n",
        "\n",
        "Unlike Python lists, NumPy arrays perform math on every element at once."
    ]),
    code("cell-007", [
        "# Exercise 2: Math operations on arrays\n",
        "prices = np.array([9.99, 14.99, 24.99, 4.99, 19.99])\n",
        "\n",
        "# Task 1: Apply a 10% discount (multiply by 0.9)\n",
        "# TODO: your code here\n",
        "discounted = \n",
        "print(\"Discounted:\", discounted)\n",
        "\n",
        "# Task 2: Add $5 shipping to each price\n",
        "# TODO: your code here\n",
        "with_shipping = \n",
        "print(\"With shipping:\", with_shipping)\n",
        "\n",
        "# Task 3: Apply 8.25% sales tax (multiply by 1.0825)\n",
        "# TODO: your code here\n",
        "with_tax = \n",
        "print(\"With tax:\", with_tax)\n",
        "\n",
        "# Task 4: Add two arrays together\n",
        "arr_a = np.array([1, 2, 3, 4, 5])\n",
        "arr_b = np.array([10, 20, 30, 40, 50])\n",
        "# TODO: your code here\n",
        "combined = \n",
        "print(\"Combined:\", combined)\n",
        "\n",
        "# ANSWER:\n",
        "# discounted = prices * 0.9\n",
        "# with_shipping = prices + 5\n",
        "# with_tax = prices * 1.0825\n",
        "# combined = arr_a + arr_b"
    ]),
    md("cell-008", [
        "## Exercise 3: 2D Arrays (Matrices)\n",
        "\n",
        "2D arrays have rows and columns, like a spreadsheet or table."
    ]),
    code("cell-009", [
        "# Exercise 3: Working with 2D arrays\n",
        "\n",
        "# Create a 2D array (3 students, 4 test scores each)\n",
        "grades = np.array([\n",
        "    [85, 90, 78, 92],   # Student 1\n",
        "    [88, 76, 95, 89],   # Student 2\n",
        "    [92, 95, 88, 91]    # Student 3\n",
        "])\n",
        "\n",
        "# Task 1: Print the shape of the array\n",
        "# TODO: your code here\n",
        "print(\"Shape:\", )\n",
        "\n",
        "# Task 2: Access Student 2's scores (row index 1)\n",
        "# TODO: your code here\n",
        "student_2 = \n",
        "print(\"Student 2 scores:\", student_2)\n",
        "\n",
        "# Task 3: Access all students' first test score (column index 0)\n",
        "# TODO: your code here\n",
        "test_1 = \n",
        "print(\"Test 1 scores:\", test_1)\n",
        "\n",
        "# Task 4: Access Student 3's third test score (row 2, col 2)\n",
        "# TODO: your code here\n",
        "single_score = \n",
        "print(\"Student 3, Test 3:\", single_score)\n",
        "\n",
        "# ANSWER:\n",
        "# print(\"Shape:\", grades.shape)\n",
        "# student_2 = grades[1]\n",
        "# test_1 = grades[:, 0]\n",
        "# single_score = grades[2, 2]"
    ]),
    md("cell-010", [
        "## Exercise 4: Array Slicing\n",
        "\n",
        "Slicing lets you select a portion of an array using `[start:stop:step]`."
    ]),
    code("cell-011", [
        "# Exercise 4: Slicing practice\n",
        "data = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])\n",
        "print(\"Full array:\", data)\n",
        "\n",
        "# Task 1: Get elements at index 1 through 4 (10, 15, 20, 25)\n",
        "# TODO: your code here\n",
        "slice1 = \n",
        "print(\"Index 1-4:\", slice1)\n",
        "\n",
        "# Task 2: Get the first 3 elements (5, 10, 15)\n",
        "# TODO: your code here\n",
        "slice2 = \n",
        "print(\"First 3:\", slice2)\n",
        "\n",
        "# Task 3: Get the last 3 elements (40, 45, 50)\n",
        "# TODO: your code here\n",
        "slice3 = \n",
        "print(\"Last 3:\", slice3)\n",
        "\n",
        "# Task 4: Get every other element (5, 15, 25, 35, 45)\n",
        "# TODO: your code here\n",
        "slice4 = \n",
        "print(\"Every other:\", slice4)\n",
        "\n",
        "# Task 5: Reverse the array\n",
        "# TODO: your code here\n",
        "slice5 = \n",
        "print(\"Reversed:\", slice5)\n",
        "\n",
        "# ANSWER:\n",
        "# slice1 = data[1:5]\n",
        "# slice2 = data[:3]\n",
        "# slice3 = data[-3:]\n",
        "# slice4 = data[::2]\n",
        "# slice5 = data[::-1]"
    ]),
    md("cell-012", [
        "## Exercise 5: Boolean Indexing\n",
        "\n",
        "Boolean indexing lets you filter arrays based on conditions — like a WHERE clause in SQL!"
    ]),
    code("cell-013", [
        "# Exercise 5: Boolean indexing\n",
        "temperatures = np.array([68, 72, 85, 90, 55, 78, 95, 62, 88, 73])\n",
        "print(\"Temperatures:\", temperatures)\n",
        "\n",
        "# Task 1: Find all temperatures above 80\n",
        "# TODO: your code here\n",
        "hot_days = \n",
        "print(\"Hot days (>80):\", hot_days)\n",
        "\n",
        "# Task 2: Find all temperatures between 70 and 85 (inclusive)\n",
        "# Hint: use & for AND, and wrap each condition in parentheses\n",
        "# TODO: your code here\n",
        "comfortable = \n",
        "print(\"Comfortable (70-85):\", comfortable)\n",
        "\n",
        "# Task 3: Count how many days were below 65\n",
        "# Hint: boolean array .sum() counts True values\n",
        "# TODO: your code here\n",
        "cold_count = \n",
        "print(\"Cold days count:\", cold_count)\n",
        "\n",
        "# ANSWER:\n",
        "# hot_days = temperatures[temperatures > 80]\n",
        "# comfortable = temperatures[(temperatures >= 70) & (temperatures <= 85)]\n",
        "# cold_count = (temperatures < 65).sum()"
    ]),
    md("cell-014", [
        "## Exercise 6: Aggregate Functions\n",
        "\n",
        "NumPy makes it easy to compute statistics on your data."
    ]),
    code("cell-015", [
        "# Exercise 6: Aggregate statistics\n",
        "exam_scores = np.array([78, 85, 92, 67, 90, 88, 73, 95, 82, 79])\n",
        "print(\"Exam scores:\", exam_scores)\n",
        "\n",
        "# Task 1: Calculate the mean (average)\n",
        "# TODO: your code here\n",
        "mean_score = \n",
        "print(f\"Mean: {mean_score}\")\n",
        "\n",
        "# Task 2: Calculate the sum\n",
        "# TODO: your code here\n",
        "total = \n",
        "print(f\"Sum: {total}\")\n",
        "\n",
        "# Task 3: Find the maximum score\n",
        "# TODO: your code here\n",
        "highest = \n",
        "print(f\"Max: {highest}\")\n",
        "\n",
        "# Task 4: Find the minimum score\n",
        "# TODO: your code here\n",
        "lowest = \n",
        "print(f\"Min: {lowest}\")\n",
        "\n",
        "# Task 5: Calculate the standard deviation\n",
        "# TODO: your code here\n",
        "spread = \n",
        "print(f\"Std Dev: {spread:.2f}\")\n",
        "\n",
        "# Task 6: Print a summary using f-strings\n",
        "# TODO: Print \"The class averaged {mean}, with scores ranging from {min} to {max}\"\n",
        "\n",
        "\n",
        "# ANSWER:\n",
        "# mean_score = np.mean(exam_scores)\n",
        "# total = np.sum(exam_scores)\n",
        "# highest = np.max(exam_scores)\n",
        "# lowest = np.min(exam_scores)\n",
        "# spread = np.std(exam_scores)\n",
        "# print(f\"The class averaged {mean_score:.1f}, with scores ranging from {lowest} to {highest}\")"
    ]),
    md("cell-016", [
        "## Submission\n",
        "\n",
        "Great work with NumPy! To get credit:\n",
        "\n",
        "1. Make sure all 6 exercises above are completed\n",
        "2. Save this notebook (File > Save a copy in Drive)\n",
        "3. Return to **HireWheel** and paste your notebook URL\n",
        "4. Answer the exit ticket questions on the lesson page"
    ])
]

# Save phase_1 notebooks
os.makedirs("/tmp/dam-build/notebooks/phase_1", exist_ok=True)
with open("/tmp/dam-build/notebooks/phase_1/DAM_Lesson_01_Getting_Started.ipynb", "w") as f:
    json.dump(make_nb(cells_01), f, indent=1)
with open("/tmp/dam-build/notebooks/phase_1/DAM_Lesson_02_NumPy_Arrays.ipynb", "w") as f:
    json.dump(make_nb(cells_02), f, indent=1)

print("L01 and L02 written.")
